.TH QYGMY 1 "July 3, 2013"

.SH NAME
qygmy - simple MPD client

.SH SYNOPSIS
.B qygmy
[--version]

.SH DESCRIPTION
.PP
.B qygmy
is a simple MPD client written in Python and Qt/PySide.

.SH OPTIONS
.TP
\fB--version\fR
Print version and exit.

.SH SEE ALSO
.PP
.B Homepage:
https://github.com/tsufeki/qygmy
.PP
.B MPD homepage:
http://musicpd.org/

.SH AUTHOR
Written by tsufeki <tsufeki@ymail.com>.
